In [3]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
X = x.reshape((3, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]]).shape

torch.Size([3, 4])

x**y表示按元素求幂

In [9]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.tensor([2, 3, 4, 5])
x**y

tensor([1.0000e+00, 8.0000e+00, 8.1000e+01, 1.0240e+03])

In [10]:
x = torch.arange(12).reshape((3, 4))
y = torch.arange(12).reshape((3, 4))
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 4,  5,  6,  7,  4,  5,  6,  7],
         [ 8,  9, 10, 11,  8,  9, 10, 11]]))

In [11]:
x.sum()

tensor(66)

广播机制。两个形状不同的张量可以通过广播机制实现按元素操作

In [12]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

a是一个三行一列的张量，b是一个一行二列的张量。维数相同，形状不同。仍然可以按元素操作。a将自身复制，成为一个三行二列的张量，b将自身复制，成为一个三行二列的张量，然后按元素操作

In [13]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
X[:, :2]

tensor([[0., 1.],
        [4., 5.],
        [8., 9.]])

In [20]:
Y = torch.arange(12).reshape((3, 4))
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

一些操作可能会导致为新结果分配新内存。用+=或者[:]进行赋值，可以保持内存地址不改变。

In [27]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [28]:
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [29]:
before = id(Y)
Y += X
id(Y) == before

True

In [23]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = Y + X
print('id(Z):', id(Z))

id(Z): 2918750926896
id(Z): 2918750926896


numpy()和torch.tensor()可以实现张量与numpy数组的类型变换

In [38]:
A = X.numpy()
B = torch.tensor(A)
type(X), type(A), type(B)

(torch.Tensor, numpy.ndarray, torch.Tensor)